Task 1 v.1
SharovSa/Programm_cpp pull request #1
Opened 2023-02-23 09:11 UTC by SharovSa

2023-03-11 13:11 UTC, alexa0o requested changes

2023-03-11 13:11 UTC, alexa0o commented on tasks/task1/adapter.hpp
> +  static bool tmp;
Неудачное имя tmp, нужно тут что-то более осмысленное написать.

2023-03-11 13:11 UTC, alexa0o commented on tasks/task1/adapter.hpp
> +mem_ptr_t global_mem_ptr;
Можно ли обойтись без глобального указателя?

2023-03-19 18:15 UTC, alexa0o requested changes
Дело твое конечно, но чего отказался от решения с указателями? Очень крутое было)

2023-03-19 18:15 UTC, alexa0o commented on tasks/task1/adapter.hpp
> +  ValueHolder_struct *structured_valueHolder;
Тут можно было бы и сразу проинициализировать

2023-03-19 18:15 UTC, alexa0o commented on tasks/task1/adapter.hpp
> +  structured_valueHolder = (ValueHolder_struct *) &valueHolder;
Каст в стиле С, у нас все же С++

2023-03-19 20:33 UTC, SharovSa commented on tasks/task1/adapter.hpp
> +mem_ptr_t global_mem_ptr;
Я не могу придумать как обойтись без неё. Максимум, я могу засунуть её в namespace. По этой причине я и решил сделать другое решение.

2023-06-03 13:48 UTC, merged