Task 2
SharovSa/Programm_cpp pull request #2
Opened 2023-03-02 18:10 UTC by SharovSa

2023-03-19 19:16 UTC, alexa0o requested changes
Надо убрать лишние файлы из pull request'a

2023-03-19 19:16 UTC, alexa0o commented on tasks/task2/transform.hpp
> +  std::vector<T> tmp;
Хочется более осмысленное имя для вектора

2023-03-19 19:16 UTC, alexa0o commented on tasks/task2/transform.hpp
> +      tmp.push_back(*ptr);
А в чем смысл пытаться копировать после эксепшена?

2023-03-19 19:16 UTC, alexa0o commented on tasks/task2/transform.hpp
> +      tmp.push_back(*ptr);
Тут забавно вышло, что ты прошел тест ponly, потому что там экспепшн при достижении границы, а потом нет. Тест я поправил) Тебе нужно будет тут подумать как копировать как можно меньше + разрешить ситуацию, когда копирования невозможны, а функции p и f работают корректно

2023-03-19 19:16 UTC, alexa0o commented on tasks/task2/transform.hpp
> +      for (int i = 0; i < tmp.size(); ++i, ++s_ptr) {
А если в массиве больше чем INT_MAX элементов?

2023-03-24 19:01 UTC, SharovSa commented
Я пытался избавится от ненужных файлов в этой ветке, в итоге вышло так, что я каким то образом запушил сюда много лишних коммитов, который я делал в другие ветки

2023-03-24 19:42 UTC, closed without merging